# Generated by Django 4.0.1 on 2022-05-11 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proudctDescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
    ]
